# Site settings
title: Michael's Blog
email: info@michaelbateman.ca
description: > # The UCC Engineering Society
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.michaelbateman.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown