# Site settings
title: Michael's Blog
email: info@michaelbateman.ca
description: > # Michael's personal
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.michaelbateman.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

exclude: [vendor]